### ISSUE TITLE
Compiler

### ISSUE THREAD

**Issue by mineo333** [mineo333/Video-Game-Design-Frost-2017#10]
For making the environment please note that Snagit, like we use in school is not free.
Here are some alternatives:

GreenShot, Shutter, Snipping Tool
I also have received reports that a compiler is hard to find. (Please tell me if I'm using the term compiler wrong)
For this issue, Unity Editor is your compiler!!!!
Meaning that you will arrange the assets in that menu to make the scene.

**Comment by 2NEON11** [comment]
Ok thanks that makes this a lot easier
