### ISSUE TITLE
Usernames

### ISSUE THREAD

**Issue by mineo333** [mineo333/Video-Game-Design-Frost-2017#13]
Can all of you please respond to this with your first name (Trust me there are too many people with your first names for you to be found) followed by your username
I need to keep track of who is saying what so I can respond accordingly.

**Comment by ParaNerd23** [comment]
Josh-ParaNerd23

**Comment by Appy360** [comment]
Appy360 - Ashwin

**Comment by mineo333** [comment]
****Thank you**** Now I have all the usernames written down
