### ISSUE TITLE
WASD or Arrow Keys?

### ISSUE THREAD

**Issue by mineo333** [mineo333/Video-Game-Design-Frost-2017#3]
Should we have WASD or arrow keys for movement.
NOTE: Currently it is arrow keys

**Comment by DarinMao** [comment]
I say it should be arrow keys by default, but the user should be able to change it to whatever they want.

**Comment by mineo333** [comment]
Okay thanks for the feedback Darin. That will be hard but I can figure it out

**Comment by mineo333** [comment]
Thank you Darin I implemented it into a panel that will be located in the home menu

**Comment by DarinMao** [comment]
It took you 17 minutes to figure that out. That's not "hard" in my book.
As a general rule of thumb, "If it doesn't take longer than an hour, then it's not hard."
