### ISSUE TITLE
Forks

### ISSUE THREAD

**Issue by DarinMao** [mineo333/Video-Game-Design-Frost-2017#5]
Here's what you said in the Wiki:

> You can add it to a forked version

Don't you mean branch? Forking is when you copy the entire repository to your own account. Branching (the one you're describing, or at least should be using) is when a separate "path" is made in the same repository (think of "master" as the main trunk in a tree). Forks are completely independent of the original repository, branches are related to the original repository.

**Comment by mineo333** [comment]
Oh wait oops
